BullBoard/BullBoard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('board.urls')),
    path('accounts/', include('allauth.urls')),
    path('account/', include('accounts.urls')),
    path('tinymce/', include('tinymce.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BullBoard/board/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('', PostList.as_view(), name='posts'),
    path('<int:pk>', PostDetail.as_view(), name='post'),
    path('create', PostCreate.as_view(), name='post_create'),
    path('<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
    path('response/<post_id>/', add_response, name='add_response'),
    path('responses', ResponsePost.as_view(), name='responses'),
    path('post_list/<int:pk>', PostListView.as_view(), name='post_list'),
    path('responses/<int:pk>/delete/', ResponseDelete.as_view(), name='response_delete'),
    path('response/<int:pk>/accept/', response_accept, name='response_accept'),
]

BullBoard/board/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class Post(models.Model):
    TYPE = (
        ('tank', 'Танки'),
        ('heal', 'Хилы'),
        ('dd', 'ДД'),
        ('buyers', 'Торговцы'),
        ('gildemaster', 'Гилдмастеры'),
        ('quest', 'Квестгиверы'),
        ('smith', 'Кузнецы'),
        ('tanner', 'Кожевники'),
        ('potion', 'Зельевары'),
        ('spellmaster', 'Мастера заклинаний'),
    )

    author_post = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, blank=True,
                                    null=True, verbose_name='Автор')
    date_time_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    category_post = models.CharField(max_length=11, choices=TYPE, default='tank')
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержание')

    def preview(self):
        return f'{self.content[:123]}...'

    def __str__(self):
        return f'{self.title}. Автор: {self.author_post.username}'

    def get_absolute_url(self):
        return reverse('post', args=[str(self.id)])

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Responses(models.Model):
    res_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    res_user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    res_content = models.TextField(verbose_name='Текст отклика')
    date_time_create = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Отклик'
        verbose_name_plural = 'Отклики'
        ordering = ['-date_time_create']

    def __str__(self):
        return str(self.res_user) + ' responses ' + str(self.res_content)

BullBoard/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
<h2>Здравствуйте! Новые статьи за последнюю неделю</h2>
<ul>
    {% for post in posts %}
        <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a> </li>
    {% endfor %}
</ul>
</body>
</html>

BullBoard/templates/post.html
{% extends 'flatpages/default.html' %}


{% block title %}
Post
{% endblock title %}
{% load static %}
{% block extrahead %}{{ block.super }}
<script src="{% static 'js/uploader.js' %}"></script>
{{ media }}
{% endblock %}

{% block content %}

{% if request.user.is_authenticated %}
<a href="{% url 'account_logout' %}" >Выйти из аккаунта</a>
{% else %}
    <a href="{% url 'account_login' %}">Войти в аккаунт</a>
{% endif %}
<br>
<br>
{% if perms.news.add_post %}
    <a href="{% url 'post_create' %}">Добавить объявление</a>
{% endif %}
<h3>Заголовок: {{ post.title }}</h3>
<h4>Дата публикации: {{ post.date_time_create|date:'d M Y' }}</h4>
<h3>Автор: {{ post.author_post.username }}</h3>
<h5>Категория: {{ post.category_post }}</h5>
<b>Содержание:</b>
<p>
    {{ post.content|safe|linebreaks }}
</p>
{% if perms.news.change_post %}
{% if post.author_post == request.user %}
<a href="{% url 'post_update' post.id %}">Изменить</a>
<br>
<a href="{% url 'post_delete' post.id %}">Удалить</a>
{% endif %}
{% endif %}
<hr>
<h2> Отклики </h2>

     {% if user.is_authenticated %}
      <form action="" method="POST" id="main_form" class="comment_form">
         <div>
             <label>Введите Ваш отклик здесь: </label>
            {{ response_form.res_content }} {% csrf_token %} <input type="submit" value=Отправить>
         </div>
         </div>
      </form>
      {% else %} <h2>Оставлять отклики могут только зарегистрированные пользователи!</h2>
      {% endif %}

      {% for response in responses %}
         {% if response.status == True %}
            <font size="4"> <b>{{ response.res_user }} : </b> {{ response.res_content }}</font><br>
         {% endif %}
      {% endfor %}
{% endblock content %}

BullBoard/templates/post_create.html
{% extends 'flatpages/default.html' %}
{% block title %}
Create
{% endblock title %}
{% load static %}
{% block extrahead %}{{ block.super }}
<script src="{% static 'js/uploader.js' %}"></script>
{{ media }}
{% endblock %}

{% block content %}

<div class="card mb-3 border-0 nth-shadow">
    <div class="card-body">
        <div class="card-title nth-card-title">
            <h1>Создание объявления</h1>
        </div>
<hr>
<form method="post" action="{% url 'post_create' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {{ form.media }}
    <div class="d-grid gap-2 d-md-block mt-2">
    <button type="submit" class="btn btn-dark">Добавить статью</button>
            </div>
        </form>

    </div>
</div>

{% endblock content %}

BullBoard/templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуй! Новая <a href="{{ link }}">статья</a> в твоём любимом разделе!</h2>
<p>{{ text }}</p>
</body>
</html>

BullBoard/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление объявления</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем '{{ object.title }}'?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}

BullBoard/templates/post_list.html
{% extends 'flatpages/default.html' %}

{% block title %}
Responses
{% endblock title %}

{% block content %}
{% if request.user.is_authenticated %}
    <a href="{% url 'account_logout' %}">Выйти из аккаунта</a>
{% else %}
    <a href="{% url 'account_login' %}">Войти в аккаунт</a>
{% endif %}
<h1>Отклики</h1>
<h3>Количество: {{ post_list|length }}</h3>
<hr>
    {% if post_list %}
        <table>
            <tr>
                <td><b>Отправитель</b></td>
                <td><b>Дата отправки</b></td>
                <td><b>Объявление</b></td>
                <td><b>Содержание</b></td>


                <td><b>Действие</b></td>

            </tr>
            {% for response in post_list %}
            <tr>
                <td>{{ response.res_user }}</a></td>
                <td>{{ response.date_time_create|date:'d M Y' }}</td>
                <td><a href="{% url 'post_list' response.res_post.id %}">{{ response.res_post.title }}</a></td>
                <td>{{ response.res_content }}</td>
                <td>
                    {% if request.user.is_authenticated %}
                        {% if response.status == False %}
                            <td><a href="{% url 'response_delete' response.id %}">Удалить</a></td>
                            <td><a href="{% url 'response_accept' response.pk %}" >Принять</a></td>
                        {% endif %}
                    {% endif %}

            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Список откликов пуст!</h2>
    {% endif %}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

BullBoard/templates/post_update.html
{% extends 'flatpages/default.html' %}
{% block title %}
Create
{% endblock title %}

{% block content %}
<h1>Изменение объявления</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Изменить" />
</form>

{% endblock content %}

BullBoard/templates/posts1.html
{% extends 'flatpages/default.html' %}
{% load static %}
{% block title %}
Posts
{% endblock title %}
{% block extrahead %}{{ block.super }}
<script src="{% static 'js/uploader.js' %}"></script>
{{ media }}
{% endblock %}

{% block content %}

{% if request.user.is_authenticated %}
    <a href="{% url 'account_logout' %}">Выйти из аккаунта</a>
{% else %}
    <a href="{% url 'account_login' %}">Войти в аккаунт</a>
{% endif %}
<h1>Все объявления</h1>
<h3>Количество: {{ posts|length }}</h3>
<hr>
{% if request.user.is_authenticated %}
    <button>
    <a class="nav-link" href="{% url 'post_create' %}">
        <h4><strong>Добавить объявление</strong></h4>
    </a>
    </button>
{% endif %}
{% if posts %}
    {% for post in posts %}
    <div class="card mb-3">
        <div class="row">

            <div class="col-8">
                <div class="card-body">
                    <h5 class="card-title">Заголовок: <a href="{% url 'post' post.id %}"> {{ post.title }}</a></h5>
                    <div class="card-subtitle">Автор: {{ post.author_post.username }}</div>
                    <p class="card-text">{{ post.content|safe|linebreaks }}</p>
                    Категория: <b>{{ post.category_post }}</b>
                    <br>
                    Дата создания: {{ post.date_time_create|date:'d M Y' }}
                    <br>
                    {% if request.user.is_authenticated %}
                        {% if post.author_post == request.user %}

                            <a href="{% url 'post_update' post.id %}">Изменить</a>
                            <a href="{% url 'post_delete' post.id %}">Удалить</a>
                        {% endif %}
                    {% endif %}
                  </div>
                </div>
            </div>
      </div>
    {% endfor %}
{% else %}
    <h2>Список объявлений пуст!</h2>
{% endif %}
{% if page_obj.has_previous %}
    <a href="?page=1">1</a>

    {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% endif %}

{{ page_obj.number }}

{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
    {% if paginator.num_pages != page_obj.next_page_number %}
           ...
        <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
    {% endif %}
{% endif %}

{% endblock content %}

BullBoard/templates/response.html
{% extends 'flatpages/default.html' %}


{% block title %}
Posts
{% endblock title %}

{% block content %}
{% if request.user.is_authenticated %}
    <a href="{% url 'account_logout' %}">Выйти из аккаунта</a>
{% else %}
    <a href="{% url 'account_login' %}">Войти в аккаунт</a>
{% endif %}

<h1>Все отклики </h1>
<h3>Количество: {{ responses|length }}</h3>
<hr>
{% if request.user.is_authenticated %}
{% if responses %}
    <table>
        <tr>
            <td><b>Отправитель</b></td>
            <td><b>Дата отправки</b></td>
            <td><b>Объявление</b></td>
            <td><b>Содержание</b></td>

                <td><b>Действие</b></td>
            {% endif %}
        </tr>
        {% for response in responses %}
            <tr>
                <td>{{ response.res_user }}</td>
                <td>{{ response.date_time_create|date:'d M Y' }}</td>
                <td><a href="{% url 'post_list' response.res_post.id %}">{{ response.res_post.title|truncatewords:10 }}</a></td>
                <td>{{ response.res_content }}</td>
                <td>
                    {% if request.user.is_authenticated %}
                        {% if response.status == False %}
                            <td><a href="{% url 'response_delete' response.id %}" >Отклонить</a></td>
                            <td><a href="{% url 'response_accept' response.pk %}" >Принять</a></td>

                        {% endif %}
                    {% endif %}
                </td>

            </tr>
        {% endfor %}
    </table>
{% else %}
    <h2>Список откликов пуст!</h2>
{% endif %}
{% if page_obj.has_previous %}
    <a href="?page=1">1</a>

    {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% endif %}

{{ page_obj.number }}

{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
    {% if paginator.num_pages != page_obj.next_page_number %}
           ...
        <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
    {% endif %}
{% endif %}

{% endblock content %}

BullBoard/templates/response_accept.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуй! Ваш отклик на <a href="{{ link }}">пост</a> был принят автором!</h2>
<p>Текст отклика: {{ text }}</p>
</body>
</html>

BullBoard/templates/response_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуй! Новый <a href="{{ link }}">отклик</a> на твою статью!</h2>
<h4>Отклик на пост: {{ post }}</h4>
<p>Текст отклика: {{ text }}</p>
</body>
</html>

BullBoard/templates/response_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление отклика</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем '{{ object.res_content }}'?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}